name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - name: Build
        run: nix develop --command mdbook build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/html

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: book/pdf/output.pdf

      - name: Deploy artifact
        uses: actions/deploy-pages@v4
